name: CI/CD for Docker Image

on:
  push:
    branches:
      - userAuthorization-service
  pull_request:
    branches:
      - userAuthorization-service

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log event
      run: |
        echo "Event: $GITHUB_EVENT_NAME"
        echo "Branch: $GITHUB_REF"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERDOCKERUSERNAME }}
        password: ${{ secrets.USERDOCKERPASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t dhanushikan/authservice:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push dhanushikan/authservice:latest

